services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/admin

      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb

  bot:
    build: .
    container_name: telegram-bot
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb:27017/admin
    env_file:
      - .env
    depends_on:
      - mongodb
    profiles:
      - with-bot

volumes:
  mongodb_data: